### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by alphapapa** [avkoval/avk-emacs-themes#1]
It would nice to have some screenshots so I can see them before installing and activating.  ;)

**Comment by avkoval** [comment]
Hi!
I've made a PR here: https://github.com/emacs-themes/emacs-themes-site/pull/6/files and when its merged it will be published on main emacs themes site http://emacsthemes.com/ and I will update README. Until then, just look into PR contents, it contains all the screenshots. ;-)
Have a good time using Emacs!
Alex

**Comment by avkoval** [comment]
Done.
